name: Build SFA with outbound_providers core from PuerNya

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TAGS: with_quic,with_gvisor,with_utls,with_clash_api

    steps:
      - name: Checkout core Repository
        uses: actions/checkout@v4
        with:
         repository: PuerNya/sing-box
         ref: building
         fetch-depth: 0

      - name: Get latest go version
        id: go_version
        run: |
          echo go_version=$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g') >> $GITHUB_OUTPUT

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'

      - name: Checkout SFA Repository
        uses: actions/checkout@v3
        with:
          repository: SagerNet/sing-box-for-android
          path: SFA
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 20

      - name: Build SFA
        run: |
          mkdir -p SFA/app/libs/
          make lib_install
          version=$(CGO_ENABLED=0 go run ./cmd/internal/read_tag)
          CGO_ENABLED=1 gomobile bind -v -androidapi 21 -javapkg=io.nekohasekai -libname=box -tags ${TAGS} -ldflags "-X github.com/sagernet/sing-box/constant.Version=${version} -buildid=" ./experimental/libbox
          cp ./libbox.aar SFA/app/libs/
          cd SFA
          echo "VERSION_NAME=${version}" > local.properties
          echo "VERSION_CODE=$(date +%Y%m%d%H)" >> local.properties
          sed -i '/signingConfigs\.release/d' app/build.gradle
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: SFA
          path: SFA/app/build/outputs/apk/
